module.exports={
    port:8080,
    appConfig:{
        columns:10,
        images:[
            'images/Symbol_1.png',
            'images/Symbol_2.png',
            'images/Symbol_3.png',
            'images/Symbol_4.png',
            'images/Symbol_5.png'
        ]
    }
}